sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm i -g now@canary
  - npm run build
  - npm run deploy

after_script: 
  - if [ "$TRAVIS_BRANCH" = "development" ]; then npm run alias:dev; fi 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run alias:prod; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; fi
  - npm run cleanup

env:
  global:
    secure: qaLfZQvE4fIu9XIn/M8lTGzqF2gFz25zW9Gx8v3xOLHrDSztNK4ZxlCdSMBn/ufCt42gnog87JuqcrOrQwKuYxVUBsQAdg0ymiRmnzIk5Om21Js1+KEt8r2RuWw1xFYaN1tNKhgtwIdPsMBp0qXmi8FWcA9GRt/sWF0H5lk3sKHSE5OOMsFwTrMU5dpAKgXC3GXmBbMOw/FoB9hW5ADJkkMR4XMf4SkBYF/guI27DwS4MD6bWCvRXm7UMeu28Z8d/5/hj+x4sERlHt9IBPCs+sZ2sz4RH6UXwoMaA6CRAR8qUsvHOB+z7XPX8FZzfKTwd9X8xHDzMgBsRu/9stIDW9Jfwl8VXyB8O9kTe8iHTWEpTgQe8l3uJ54MaljlFc783/QWlz1OLQxtxbC0kt4Gfs6UTAkVQUrPhV3th5wLvBb7qXfbHoXO3dToaM8MbY/93ar/HTX/W4Yl4tJeZCKkfn0/v+FY1Iu1mIi5Mcvol5Z/R+TXN0kgyuofFAcnOGcTKgK3p2mfLAAfggOXRQoCVnhO8Txe4SUHPSNhboAaewsNu1UHY9XYJXamL/BVZRcQzjQhYMM6EIVw6FUG+vEGES5ny478/pANt6txsU79zWrGeRodgqbXY9yss6A2M2nDAMKzQLPPd/HoDLIYd4XpZ5d0gVgNofUdBjNynLGhZQE=
